name: PushNewReleaseV2

on: 
  push:
    branches:
    - "main"
    tags:
    - '*.*.*'

jobs:

  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v2
        
      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name: Get release version
        run: |
          echo $RELEASE_VERSION
          echo ${{ env.RELEASE_VERSION }}
        
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 18.x
          
      - name: get-npm-version
        id: package-version
        uses: martinbeentjes/npm-get-version-action@v1.1.0
        
      - uses: ncipollo/release-action@v1
        with:
          name: '${{ steps.package-version.outputs.current-version }}'
          artifacts: "release.tar.gz,foo/*.txt"
          bodyFile: "body.md"
          skipIfReleaseExists: true
          commit: "main"
