name: PushNewReleaseV2

on: 
  push:
    branches:
    - "release/*"
    tags:
    - '*'

jobs:

  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v2
      - uses: ncipollo/release-action@v1
        with:
          name: '${{ steps.package-version.outputs.current-version }}'
          artifacts: "release.tar.gz,foo/*.txt"
          bodyFile: "body.md"
          skipIfReleaseExists: true
          commit: "main"
