name: 'Release'

on:
  push:
    branches:
      - "main"
  workflow_dispatch:
    inputs:
      semver:
        description: 'Which version you want to increment? Use MAJOR, MINOR or PATCH'
        required: true
        default: 'PATCH'
      label:
        description: 'Add Labels. i.e final, alpha, rc'
        required: true
        default: ' Stable'

jobs:
  release:
    name: 'Release'
    runs-on: 'ubuntu-latest'

    steps:
      - name: 'Checkout'
        uses: actions/checkout@v2
        
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 18.x
          
      - name: get-npm-version
        id: package-version
        uses: martinbeentjes/npm-get-version-action@v1.1.0

      # ...
      - name: '👷‍♂️ Build'
        run: |
          echo "BUILD COMPLETE 👍"
      # ...
      - name: '🧪 TEST'
        run: |
          echo "TESTS PASSED 🎉"
      - uses: 'rui-costa/action-automatic-semver-releases@latest'
        name: "Automatic Release Update"
        with:
          TOKEN: '${{ secrets.GITHUB_TOKEN }}'
          SEMVER: '${{ steps.package-version.outputs.current-version }}'
          LABEL: 'Alpha'
          NOTES: '${{ steps.gen-notes.outputs.notes }}'
