
# Makes new release when package.json version is changed

name: PublishNewRelease

on:
  push:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  make-release:
    runs-on: "ubuntu-latest"
    steps:
    
      - uses: actions/checkout@v2
    
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 18.x
          
    
      - name: get-npm-version
        id: package-version
        uses: martinbeentjes/npm-get-version-action@v1.1.0
          
          
      - name: Create Tag
        uses: negz/create-tag@v1
        with:
          version: ${{ steps.package-version.outputs.current-version }}
          message: ${{ steps.package-version.outputs.current-version }}
          token: ${{ secrets.GITHUB_TOKEN }}


      - name: Publish Release
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.ACTION_CRON_JOB_SECRET }}"
          title: "${{ steps.package-version.outputs.current-version }}"
          prerelease: true
          automatic_release_tag: "Alpha v${{ steps.package-version.outputs.current-version }}"

